version: "3.7"
services:
  mongoDatabase:
    image: mongo:4.4-rc
    container_name: mongoDatabase
    hostname: mongoDatabase
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - main-network
    command: ["--bind_ip", "0.0.0.0"]
  vegetationRecordService:
    build:
      context: .
      dockerfile: Dockerfile
    image: vegetation-record-service
    container_name: VegetationRecordService
    hostname: has.prod.vegetation-record-service
    restart: on-failure
    depends_on:
      - mongoDatabase
    links:
      - mongoDatabase
    ports:
      - "4000:4000"
    expose:
      - "4000"
    networks:
      - main-network
networks:
  main-network:
    name: "PlantNetwork"
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
